version: '3'
services:
  redis: 
    image: redis:alpine
    container_name: sc-redis
    restart: always
    volumes:
      - ../data/redis:/data
      - ./app/redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=123456
    networks:
      - sc-net
    ports:
      - 6379:6379
    env_file: .env

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: sc-rabbitmq
    restart: always
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - sc-net
    ports:
      - 15672:15672
      - 5672:5672
    env_file: .env

#  mysql:
#    image: mysql:5.7
#    container_name: sc-mysql
#    restart: always
#    networks:
#      - sc-net
#    ports:
#      - 3306:3306
#    volumes:
#      - ../data/mysql:/var/lib/mysql
#    environment:
#      TZ: Asia/Shanghai
#      MYSQL_ROOT_PASSWORD: root123
#
#  mysql-init:
#    image: mysql:5.7
#    command: /init-db.sh
#    networks:
#      - sc-net
#    volumes:
#      - ../db/auth:/sql/auth
#      - ../route-server-zuul/src/main/resources/h2:/sql/gateway
#      - ./init-db.sh:/init-db.sh
#    environment:
#      MYSQL_ROOT_PASSWORD: root123

networks:
  sc-net:
    external: false